/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var ScalarMotionPrototype_pb = require('./ScalarMotionPrototype_pb.js');
goog.object.extend(proto, ScalarMotionPrototype_pb);
var Vector3MotionPrototype_pb = require('./Vector3MotionPrototype_pb.js');
goog.object.extend(proto, Vector3MotionPrototype_pb);
goog.exportSymbol('proto.com.domeime.vmn.MotionPrototype', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.domeime.vmn.MotionPrototype = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.com.domeime.vmn.MotionPrototype.oneofGroups_);
};
goog.inherits(proto.com.domeime.vmn.MotionPrototype, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.domeime.vmn.MotionPrototype.displayName = 'proto.com.domeime.vmn.MotionPrototype';
}

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.com.domeime.vmn.MotionPrototype.oneofGroups_ = [[3,4]];

/**
 * @enum {number}
 */
proto.com.domeime.vmn.MotionPrototype.ImplCase = {
  IMPL_NOT_SET: 0,
  SCALAR: 3,
  VECTOR3: 4
};

/**
 * @return {proto.com.domeime.vmn.MotionPrototype.ImplCase}
 */
proto.com.domeime.vmn.MotionPrototype.prototype.getImplCase = function() {
  return /** @type {proto.com.domeime.vmn.MotionPrototype.ImplCase} */(jspb.Message.computeOneofCase(this, proto.com.domeime.vmn.MotionPrototype.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.domeime.vmn.MotionPrototype.prototype.toObject = function(opt_includeInstance) {
  return proto.com.domeime.vmn.MotionPrototype.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.domeime.vmn.MotionPrototype} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.domeime.vmn.MotionPrototype.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    serialid: jspb.Message.getFieldWithDefault(msg, 2, 0),
    scalar: (f = msg.getScalar()) && ScalarMotionPrototype_pb.ScalarMotionPrototype.toObject(includeInstance, f),
    vector3: (f = msg.getVector3()) && Vector3MotionPrototype_pb.Vector3MotionPrototype.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.domeime.vmn.MotionPrototype}
 */
proto.com.domeime.vmn.MotionPrototype.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.domeime.vmn.MotionPrototype;
  return proto.com.domeime.vmn.MotionPrototype.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.domeime.vmn.MotionPrototype} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.domeime.vmn.MotionPrototype}
 */
proto.com.domeime.vmn.MotionPrototype.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setSerialid(value);
      break;
    case 3:
      var value = new ScalarMotionPrototype_pb.ScalarMotionPrototype;
      reader.readMessage(value,ScalarMotionPrototype_pb.ScalarMotionPrototype.deserializeBinaryFromReader);
      msg.setScalar(value);
      break;
    case 4:
      var value = new Vector3MotionPrototype_pb.Vector3MotionPrototype;
      reader.readMessage(value,Vector3MotionPrototype_pb.Vector3MotionPrototype.deserializeBinaryFromReader);
      msg.setVector3(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.domeime.vmn.MotionPrototype.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.domeime.vmn.MotionPrototype.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.domeime.vmn.MotionPrototype} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.domeime.vmn.MotionPrototype.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getSerialid();
  if (f !== 0) {
    writer.writeUint32(
      2,
      f
    );
  }
  f = message.getScalar();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      ScalarMotionPrototype_pb.ScalarMotionPrototype.serializeBinaryToWriter
    );
  }
  f = message.getVector3();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      Vector3MotionPrototype_pb.Vector3MotionPrototype.serializeBinaryToWriter
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.com.domeime.vmn.MotionPrototype.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.com.domeime.vmn.MotionPrototype.prototype.setName = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional uint32 serialId = 2;
 * @return {number}
 */
proto.com.domeime.vmn.MotionPrototype.prototype.getSerialid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.com.domeime.vmn.MotionPrototype.prototype.setSerialid = function(value) {
  jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional ScalarMotionPrototype scalar = 3;
 * @return {?proto.com.domeime.vmn.ScalarMotionPrototype}
 */
proto.com.domeime.vmn.MotionPrototype.prototype.getScalar = function() {
  return /** @type{?proto.com.domeime.vmn.ScalarMotionPrototype} */ (
    jspb.Message.getWrapperField(this, ScalarMotionPrototype_pb.ScalarMotionPrototype, 3));
};


/** @param {?proto.com.domeime.vmn.ScalarMotionPrototype|undefined} value */
proto.com.domeime.vmn.MotionPrototype.prototype.setScalar = function(value) {
  jspb.Message.setOneofWrapperField(this, 3, proto.com.domeime.vmn.MotionPrototype.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 */
proto.com.domeime.vmn.MotionPrototype.prototype.clearScalar = function() {
  this.setScalar(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.domeime.vmn.MotionPrototype.prototype.hasScalar = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional Vector3MotionPrototype vector3 = 4;
 * @return {?proto.com.domeime.vmn.Vector3MotionPrototype}
 */
proto.com.domeime.vmn.MotionPrototype.prototype.getVector3 = function() {
  return /** @type{?proto.com.domeime.vmn.Vector3MotionPrototype} */ (
    jspb.Message.getWrapperField(this, Vector3MotionPrototype_pb.Vector3MotionPrototype, 4));
};


/** @param {?proto.com.domeime.vmn.Vector3MotionPrototype|undefined} value */
proto.com.domeime.vmn.MotionPrototype.prototype.setVector3 = function(value) {
  jspb.Message.setOneofWrapperField(this, 4, proto.com.domeime.vmn.MotionPrototype.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 */
proto.com.domeime.vmn.MotionPrototype.prototype.clearVector3 = function() {
  this.setVector3(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.domeime.vmn.MotionPrototype.prototype.hasVector3 = function() {
  return jspb.Message.getField(this, 4) != null;
};


goog.object.extend(exports, proto.com.domeime.vmn);
