/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var Vector3_pb = require('./Vector3_pb.js');
goog.object.extend(proto, Vector3_pb);
goog.exportSymbol('proto.com.domeime.vmn.Vector3MotionPrototype', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.domeime.vmn.Vector3MotionPrototype = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.domeime.vmn.Vector3MotionPrototype, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.domeime.vmn.Vector3MotionPrototype.displayName = 'proto.com.domeime.vmn.Vector3MotionPrototype';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.domeime.vmn.Vector3MotionPrototype.prototype.toObject = function(opt_includeInstance) {
  return proto.com.domeime.vmn.Vector3MotionPrototype.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.domeime.vmn.Vector3MotionPrototype} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.domeime.vmn.Vector3MotionPrototype.toObject = function(includeInstance, msg) {
  var f, obj = {
    min: (f = msg.getMin()) && Vector3_pb.Vector3.toObject(includeInstance, f),
    max: (f = msg.getMax()) && Vector3_pb.Vector3.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.domeime.vmn.Vector3MotionPrototype}
 */
proto.com.domeime.vmn.Vector3MotionPrototype.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.domeime.vmn.Vector3MotionPrototype;
  return proto.com.domeime.vmn.Vector3MotionPrototype.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.domeime.vmn.Vector3MotionPrototype} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.domeime.vmn.Vector3MotionPrototype}
 */
proto.com.domeime.vmn.Vector3MotionPrototype.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new Vector3_pb.Vector3;
      reader.readMessage(value,Vector3_pb.Vector3.deserializeBinaryFromReader);
      msg.setMin(value);
      break;
    case 2:
      var value = new Vector3_pb.Vector3;
      reader.readMessage(value,Vector3_pb.Vector3.deserializeBinaryFromReader);
      msg.setMax(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.domeime.vmn.Vector3MotionPrototype.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.domeime.vmn.Vector3MotionPrototype.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.domeime.vmn.Vector3MotionPrototype} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.domeime.vmn.Vector3MotionPrototype.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMin();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      Vector3_pb.Vector3.serializeBinaryToWriter
    );
  }
  f = message.getMax();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      Vector3_pb.Vector3.serializeBinaryToWriter
    );
  }
};


/**
 * optional Vector3 min = 1;
 * @return {?proto.com.domeime.vmn.Vector3}
 */
proto.com.domeime.vmn.Vector3MotionPrototype.prototype.getMin = function() {
  return /** @type{?proto.com.domeime.vmn.Vector3} */ (
    jspb.Message.getWrapperField(this, Vector3_pb.Vector3, 1));
};


/** @param {?proto.com.domeime.vmn.Vector3|undefined} value */
proto.com.domeime.vmn.Vector3MotionPrototype.prototype.setMin = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.com.domeime.vmn.Vector3MotionPrototype.prototype.clearMin = function() {
  this.setMin(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.domeime.vmn.Vector3MotionPrototype.prototype.hasMin = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional Vector3 max = 2;
 * @return {?proto.com.domeime.vmn.Vector3}
 */
proto.com.domeime.vmn.Vector3MotionPrototype.prototype.getMax = function() {
  return /** @type{?proto.com.domeime.vmn.Vector3} */ (
    jspb.Message.getWrapperField(this, Vector3_pb.Vector3, 2));
};


/** @param {?proto.com.domeime.vmn.Vector3|undefined} value */
proto.com.domeime.vmn.Vector3MotionPrototype.prototype.setMax = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.com.domeime.vmn.Vector3MotionPrototype.prototype.clearMax = function() {
  this.setMax(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.domeime.vmn.Vector3MotionPrototype.prototype.hasMax = function() {
  return jspb.Message.getField(this, 2) != null;
};


goog.object.extend(exports, proto.com.domeime.vmn);
